### ISSUE TITLE
README

### ISSUE THREAD

**Issue by xXWilliaN12Xx** [Harunookami/100-dias-programando-em-java#1]
# Olá Harunookami

Eu recomendo fortemente adicionar um arquivo README ao seu repositório no GitHub. O README é a primeira impressão que os visitantes terão do seu projeto e pode fornecer informações essenciais sobre o que seu projeto faz, como instalá-lo e usá-lo, além de quaisquer outros detalhes importantes.

#

## Com carinho: xXWilliaN12Xx

**Comment by Harunookami** [comment]
Olá, obrigada pela dica. Irei implementar isso nos proximos posts.

**Comment by xXWilliaN12Xx** [comment]
Continue com os estudos sem parar!!
